# Optional citation source list for future auto-updates.
# Keep empty for fully manual curation, or add DOI/PubMed/ORCID identifiers here.

# - id: doi:10.1146/annurev-vision-101322-012348
# - id: doi:10.1038/s41467-024-53326-x
